version: '3.8'
dockerversion: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: project82_postgres_db
    restart: always
    environment:
      POSTGRES_USER: project82_user
      POSTGRES_PASSWORD: project82_password
      POSTGRES_DB: project82_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
